### ISSUE TITLE
Do not stop propagation by default

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-pointer-events#15]
With elm 0.19 we were supposed to get control over sync or async processing of events. However, due to issues with how the elm virtual dom handles events, this change has been partially cancelled.

Now, only if an event stops propagation, it will trigger a sync DOM repaint. The reason for this strange behavior is explained in elm/virtual-dom#125. So even if stopping propagation leads to less surprising events, it should not be the default due to performance concerns for high frequency events such as touch move.

The question is should I only change default for the high frequency events (mouse move, touch move, dragging, etc.) at the risk of consistency, or should I not stop propagation for all events, at the risk of some surprises (events propagation can be weird, especially with layout arranging libraries like elm-ui).

**Comment by rtfeldman** [comment]
A bit of context might be useful here!

So in 0.18, all events were processed asynchronously. As far as I know, the reasons for introducing the possibility of handling them synchronously were:

1. If you set `value` in an async handler on a text input, the cursor could jump.
2. For security reasons, some browser APIs (e.g. clipboard stuff) can only be invoked synchronously inside an event handler from user input event.

The original 0.19 design offered the possibility of choosing between sync and async. However, as https://github.com/elm/virtual-dom/issues/125 noted, choosing sync without also using `stopPropagation` led to surprising bugs.

So the question was: are there any use cases where *both* of these are important?

1. I need my event handling to be done synchronously
2. I also need propagation to happen so that I can handle the event further up the chain than the original element

We couldn't come up with any use cases where *both* requirements existed at once, so mandating `stopPropagation` for synchronous events seemed like a good solution. That rules out the bug, while leaving the door open to expand the API in a backwards-compatible way if it turns out there are compelling use cases we missed.

For pointer events, I'd say that since the 0.18 release used 100% async events (since that was all that existed at the time!) then having the package continue to work the same way in 0.19 (that is, all events are still handled asynchronously) seems like the least surprising way to proceed.

**Comment by rtfeldman** [comment]
As an aside, if anyone reports a use case where they need both synchronous pointer event handling *and* propagation, please let me know!

**Comment by mpizenberg** [comment]
# About this library

> For pointer events, I'd say that since the 0.18 release used 100% async events (since that was all that existed at the time!) then having the package continue to work the same way in 0.19 (that is, all events are still handled asynchronously) seems like the least surprising way to proceed.

Well, in 0.18 we were exactly in the (impossible now) async + stop propagation case. So whatever the choice, there will be differences. I believe continuing to stop propagation at the price of DOM recomputation will lead to less surprises (with regard to 0.18 behavior) than no immediate DOM recomputation but not stopping propagation. I've no concrete proof of that though, hence the question asked here and on discourse, "should I continue to stop propagation by default for low frequency events (downs, ups, clicks, ...)?".

# About issue 125

> 1. If you set value in an async handler on a text input, the cursor could jump.
>
> 2. For security reasons, some browser APIs (e.g. clipboard stuff) can only be invoked synchronously inside an event handler from user input event.

I'm not familiar with (1) since I'm mostly focused on "non-website" applications. I've face (2) a few times and I'm grateful that sync events were introduced, since at the same time, more JS injection were prevented. In my case specifically:

```elm
attribute "onpointerdown" "event.target.setPointerCapture(event.pointerId);"
```

Is not possible anymore. Calling `setPointerCapture()` in 0.18 was not possible in ports so the changes mentionned in issue elm/html#56 were making it impossible to do in elm. Now with synchronous ports calls in 0.19 we can do it in ports. BTW, at the time, I added a comment with such example in that issue since Evan is often asking about concrete example. The comment got deleted with no explanation, probably because it was a bit late in the issue life time, I felt quite bad at the time honestly.

Back on track ... I have a feeling that many things are treated as equivalent or at least confusing to me in what we call "sync" processing of events. I believe there are three different concepts that play a role here:

a. Sync call of the update call with the decoded event.
b. Sync call of the port code called by a command generated in update.
c. Sync re-computation of the DOM (not only VDOM).

I think to solve (2) and usecases like mine, only (a) and (b) are necessary. However, if I understand correctly, (1) is only solvable if we also have (c). And issue 125 is actually happening because of (c). I would like to have control over (a) and (b) in the design of Elm. I don't mind if (c) forces stop propagation. This is diverging a bit from the original question in this issue but if you are interested in the discussion, I could open a different issue about this distinction in elm/virtual-dom.

**Comment by mpizenberg** [comment]
Not stopping propagation for drag events put me in an impossible situation.

I need to prevent drop from happening outside of the droppable area (like image drop that inadvertly replaces the page). So the surrounding of the droppable area must have `event.dataTransfert.dropEffect = 'none'`. As a result, a dragover event get catched by this rule when propagating outside, resulting in no drop being possible.

So I'll keep the "stop propagation" as a default for drag and drop events.

**Comment by mpizenberg** [comment]
Change done in 6fd75add
