### ISSUE TITLE
Consider not stripping examples from release package

### ISSUE THREAD

**Issue by shaydon** [mpizenberg/elm-pointer-events#20]
I see from #10 that this was intentional, but it does mean that someone like me reading the docs at [https://package.elm-lang.org/packages/mpizenberg/elm-pointer-events/latest/](https://package.elm-lang.org/packages/mpizenberg/elm-pointer-events/latest/) and clicking on 'Browse Source' in search of the examples will see them as missing until they realise they have to switch to the master branch. ('Browse Source' links to the release tag.)

Alternatively you could include a link to the master branch examples folder in the Readme, though the examples might have changed since you did the release.

Stripping the package doesn't seem to be required practice - or at least, Evan didn't do it when releasing his recent elm/file ([https://github.com/elm/file/tree/1.0.1](https://github.com/elm/file/tree/1.0.1)).

Thanks for the excellent package.

**Comment by mpizenberg** [comment]
Ha, I was wondering if it would eventually have negative consequences. Thanks for the feedback! You're probably right about the examples. I started to do this to limit the network cost of people installing their packages (hate waiting on npm downloads). elm-explorations/webgl is a well known package doing this also. But I guess since the examples here are very light (only made of text) you're right about the advantage of keeping them with the published version tag. Also now elm has a cache for installed packages so it might only get downloaded once anyway.

I have to update the package with a breaking change soon (cf #18). I was procrastinating this during the holidays, have to do it ^^.

Thanks again, it will be done very soon, and happy new year!

**Comment by shaydon** [comment]
It's minor of course, and totally your call - I just thought it was worth mentioning my experience as a new user. I see webgl does link to its examples early in the Readme, having them easy to find one way or the other seems like the most important thing.

Happy New Year to you too!

**Comment by mpizenberg** [comment]
4.0.0 published, the examples are there ;)
