### ISSUE TITLE
Add meta key in Mouse Event

### ISSUE THREAD

**Issue by loicknuchel** [mpizenberg/elm-pointer-events#26]
Hi,

I saw that meta key is not provided on purpose for Mouse Event because it's not supported on Linux (https://github.com/mpizenberg/elm-pointer-events/blob/master/src/Html/Events/Extra/Mouse.elm#L110)
Still, on Mac, this key is the most used one, like the ctrl key in Linux, and with this choice I can't provide a ctrl+click experience on Mac.

Do you have a workaround for that? (except from opt-out from the decoder).
Would you consider changing that or providing a workaround?

Thanks

**Comment by mpizenberg** [comment]
Hi Loïc, I haven't thought too much about it. I'm not super available right
now as I'm changing jobs and changing cities (moving from Caen to
Toulouse). But if you have ideas on how to improve that in a way that is
cross platform don't hesitate to let me know. We can also take few minutes
to discuss this over a call (let me know via slack is probably the easiest).

Otherwise, my feeling is that I see elm-pointer-events as an easy to use
package to prototype UXs, but then I usually just extract the decoders I
need from the code to have something more tailored and performant. So don't
hesitate to just extract and copy paste whatever you need.

**Comment by mpizenberg** [comment]
If we want to add it, one option is to decode and fall back to either `False` or the `Ctrl` key.

**Comment by lydell** [comment]
Also note that ctrl+click on macOS opens the context menu and does not trigger any event in JavaScript.

Alternatives:

- Also remove support for ctrl since it’s not cross platform either.
- Expose both ctrl and meta/cmd and let the user handle it.
- Expose a single field called _something_ that is `ctrl || meta`. That’s how I usually implement keyboard shortcuts on the web to support both Windows/Linux and macOS at the same time. Not sure if this excludes any use cases though.

Thanks for the pointer (no pun intended) about copying the parts I need and only using this for prototyping. The app I’m working on is definitely graduating from prototype stage now and needs cmd shortcuts on macOS.

**Comment by mpizenberg** [comment]
The option I prefer would be to support both ctrl and meta, with decoders defaulting to false if the key is not available. If anyone wants to implement this, I'd be happy to include it.

**Comment by mpizenberg** [comment]
Thanks both, for the issue and PR. The update with the support of the meta key is now published as version 5.0.0
