### ISSUE TITLE
Pointer capture, or how to handle pointer release outside the drawing area

### ISSUE THREAD

**Issue by robx** [mpizenberg/elm-pointer-events#4]
I'd like to discuss whether and how to handle [setPointerCapture](https://www.w3.org/TR/pointerevents/#widl-Element-setPointerCapture-void-long-pointerId). Alternatively, whether or how `elm-pointer-events` could be used for a drawing app that wants to correctly end drawing.

My understanding is that pointer events unify mouse events (never capture) and touch events (touchstart captures) by providing the `{set,release}PointerCapture` methods on elements, and not capturing by default.

I've been working on handling pointer release correctly for drawing applications. Compare https://github.com/robx/elm-pointer-draw (live at http://vllmrt.net/elm-pointer-draw/plain/) for a rather minimal demo, which uses current master of elm-pep. The aim is to be able to draw using mouse or touch input, and to have drawing stop when the pointer is released anywhere.

From my investigation, it seems that the correct way to handle this with "Pointer Events" is by calling `setPointerCapture` on `pointerdown`. I've implemented that in a minimal way, compare https://github.com/robx/elm-pointer-draw/tree/capture (live at http://vllmrt.net/elm-pointer-draw/capture/). The changes touch `elm-lang/virtual-dom` and the whole dependency stack. The core change is here: https://github.com/elm-lang/virtual-dom/compare/master...robx:capture

I'll file a PR separately for the corresponding elm-pep change, but of course that doesn't make sense as long as Elm doesn't make use of the methods. And obviously this isn't the place to make the changes to virtual-dom, but I think it'd be better to discuss at this level first!

**Comment by mpizenberg** [comment]
> I'd like to discuss whether and how to handle setPointerCapture.

I didn't know about [pointer capture][ptr-capture], it does seem quite interesting. The compatibility table however is quite poor (see [mdn doc][mdn-setPointerCapture]).

> My understanding is that pointer events unify mouse events (never capture) and touch events (touchstart captures) by providing the {set,release}PointerCapture methods on elements, and not capturing by default.

From my tests with pointer events in Chrome, it does set pointer capture for touch-like events (captured on my phone) but not for mouse-like events (not captured with mouse on laptop).

> The core change is here: elm-lang/virtual-dom@master...robx:capture

I've looked at the diff and it seems to me that there are few issues. Pointer capture is not generic enough to go into the html `Options` that are used for all events. An alternative would be to provide a function like `onPointer` distinct of `onWithOptions` that would be used for pointer-like events and have its own option type. The differences would be:

```elm
onWithOptions : String -> Options -> Decoder msg -> Attribute msg

onPointer : String -> Options -> PointerOptions -> Decoder msg -> Attribute msg
```

This would also rectify the fact that you are currently calling `event.pointerId` when `options.capturePointer` could have been used with something else than a pointer event. According to [w3c documentation][ptr-capture], this would result in a `DOMException` of type `InvalidPointerId`. (And that's if `setPointerCapture` is also implemented).

Now I also get that for testing purpose only, it was easier to deal directly with the original `Options` type.

Due to the compatibility issues, it's going to be pretty hard to convince Evan to provide such a change, but I guess it's a first step to make them aware of the issue at least. Regarding the compatibility issue btw, it puzzles me that mdn says that Chrome has no support of `setPointerCapture` and yet your example web app is working in Chrome, wich does not execute the polyfill.

[ptr-capture]: https://www.w3.org/TR/pointerevents/#dfn-pointer-capture
[mdn-setPointerCapture]: https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture

**Comment by robx** [comment]
I realize that these aren't changes that would make it to the core libraries easily. I was just trying to explore how things could be done, "correctly".

I found a good-enough way without core changes now:

```
capturePointerDown : Html.Attribute msg
capturePointerDown = Html.attribute "onpointerdown" "event.target.setPointerCapture(event.pointerId);"
```

Maybe `event.currentTarget` would be better, but that didn't work for me for some reason. Do you think this would be a good addition to `elm-pointer-events`? I could make a PR.

Will work on the elm-pep pointer capture PR anyway, because that's still needed.

**Comment by mpizenberg** [comment]
Thanks for this! I'll probably take some time to get back here (and elm-pep). With Christmas / NYE holidays and also think about this a little, finding the best way to make it fit in the package. But I'm not forgetting ;) Merry Christmas!

**Comment by robx** [comment]
Sure same to you!

**Comment by mpizenberg** [comment]
Hi, so I've been trying to use the `onpointerdown` attribute trick without success ...
Here is my attempt with latest elm-pep PR version: https://ellie-app.com/fHvQGgJ5ha1/0
I hoped that when clicking in the box and then continuing outside, it would continue to trigger events but it doesn't (latest firefox and chrome tested).

Am I missing something?

**Comment by robx** [comment]
Yup, minor mistake, the event thingy should be an expression not a function, i.e., remove the "event =>": https://ellie-app.com/jqMpw8WQja1/0

(I did the same of course at first.)

**Comment by mpizenberg** [comment]
It was under my nose ... Thanks !

I've reviewed the PR on elm-pep. Now waiting for your approval or remarks and I think it's ready to be merged.

Regarding the initial alternative of adding pointer capture to html options, I think it is not yet mature enough to reach the elm virtual dom implementation any time soon. I'm more in favor of talking about the `attribute` trick in the documentation of the package. It is very relevant to this package, and the question of following mouse event outside of original element has been asked already ([bbdbdd][reddit-1]).

[reddit-1]: https://www.reddit.com/r/elm/comments/7gksya/pointer_mousetouchpointer_events_community/dqk1emq/

**Comment by mpizenberg** [comment]
I included the pointer capture tip in readme documentation so I think we are good now. See commit 849b1042
