### ISSUE TITLE
Mouse.clicks

### ISSUE THREAD

**Issue by rtfeldman** [mpizenberg/elm-pointer-events#9]
I'd like to use both this package as well as [`elm-lang/mouse`](http://package.elm-lang.org/packages/elm-lang/mouse/latest) for [`Mouse.clicks`](http://package.elm-lang.org/packages/elm-lang/mouse/1.0.1/Mouse#clicks).

This is currently impossible because both packages expose a module called `Mouse`, so as soon as I install both and write `import Mouse`, I get an error because it's an ambiguous import (due to https://github.com/elm-lang/elm-compiler/issues/1625).

`elm-lang/mouse` only exposes 4 subscriptions. What do you think of adding `elm-lang/mouse` as a dependency to this library and exposing them as well?

**Comment by mpizenberg** [comment]
Thanks for the remark! I've always played with elm apps having full control over DOM so didn't realized this unfortunate name collision. I don't mind re-exposing those.

Regarding the API, I've used the tuple convention with floats `( Float, Float )` in the rest of the package. In elm-lang/mouse, it's a record of integers that is used `{ x : Int, y : Int }`. Do you think I should

(1) simply expose as-is, noting that this is here mostly to avoid namespace collision
(2) `Sub.map` the subscriptions to present at as a `( Float, Float )`

I'm more for (1) since (2) would make no sense if I don't return a `Mouse.Event` anyway.

**Comment by mpizenberg** [comment]
Actually I don't know how to expose them. I also cannot import elm-lang `Mouse` module without having a compiler error ...

**Comment by rtfeldman** [comment]
Ha, good point!

I guess we're stuck then.

**Comment by mpizenberg** [comment]
It seems that `Mouse` doesn't exist anymore in the new elm and that the only possible collision left is with zwilias/elm-touch-events `Touch` module. Do you know if there is a mechanism in 0.19 to prevent those kind of collisions? Otherwise, I will probably try to find a fitting prefix namespace.

**Comment by mpizenberg** [comment]
Modules are now all namespaced under `Html.Events.Extra...` so there are no conflicts anymore. More info in [changelog](https://github.com/mpizenberg/elm-pointer-events/blob/master/CHANGELOG.md).
